### ISSUE TITLE
Jetpack 4.2 Ubuntu 18.04 i2c error

### ISSUE THREAD

**Issue by ghost** [jetsonhacks/JHPWMDriver#3]
When I try this with Jetpack 4.2 with TX2
https://devtalk.nvidia.com/default/topic/1061878/jetson-tx2/i2c-library-not-working-properly-connect-with-pca9685-/
there is same problem to i2c.
What should I do?

**Comment by rdelfin** [comment]
There's a pull request with a fix: https://github.com/jetsonhacks/JHPWMDriver/pull/2
